### ISSUE TITLE
Color picker param not available in UI

### ISSUE THREAD

**Issue by tikidave** [tradovate/custom-indicators#2]
Inside the `predef` module, there is a `color` option:
```javascript
color(defValue) {
    return {
        type: ParamType.COLOR,
        def: defValue
    };
}
```
I have implemented it in the `params` code this way:
```javascript
params: {
    upColor: predef.paramSpecs.color('lime'),
    downColor: predef.paramSpecs.color('red'),
},
```
When the indicator is added, the color pickers are not available in the UI:

![image](https://user-images.githubusercontent.com/132237/45757531-95d3d380-bbf1-11e8-9af8-2c5672ed806b.png)

However it does pick up the default `props` in the indicator:
```javascript
style: {
    value: {
        color: close > priorClose ? this.props.upColor : this.props.downColor
    }
}
```
![image](https://user-images.githubusercontent.com/132237/45757669-ed723f00-bbf1-11e8-9afc-48b80b42027c.png)

**Comment by victorwins** [comment]
Here is a spec for parameter: https://tradovate.github.io/custom-indicators/params.html
When a new parameter type will be available on all our platforms, the doc will be updated.
